import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import '../styles/globals.css';
import { useState } from 'react';

export default function Home() {
  async function handleSubmit(e) {
  e.preventDefault();

  const formData = {};

  Array.from(e.currentTarget.elements).forEach(field => {
    if ( !field.name ) return;
    formData[field.name] = field.value;
  });

  await fetch('/api/mail', {
    method: 'POST',
    body: JSON.stringify(formData)
  });
    
    function reset(){
        var element = document.getElementById(" contactMe ");
      element.reset();
      }
}
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.grid}>
          <form method="post" onSubmit={handleSubmit} id="contactMe">
            <p>
              <label htmlFor="name">Name</label>
              <input id="name" type="text" name="name" />
            </p>
            <p>
              <label htmlFor="email">Email</label>
              <input id="email" type="text" name="email" />
            </p>
            <p>
              <label htmlFor="message">Message</label>
              <textarea id="message" name="message" />
            </p>
            <p>
              <button onClick="reset()">Submit</button>
            </p>
          </form>
        </div>
      </main>
    </>
  )
}
